apiVersion: v1
kind: Service
metadata:
  name: appmesh-gateway
  labels:
    app: appmesh-gateway
  annotations:
    gateway.appmesh.k8s.aws/expose: "false"
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: appmesh-gateway
