apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmesh-gateway
spec:
  template:
    spec:
      containers:
        - name: controller
          command:
            - ./appmesh-gateway
            - --opt-in=true
            - --gateway-mesh=appmesh
            - --gateway-name=$(POD_SERVICE_ACCOUNT)
            - --gateway-namespace=$(POD_NAMESPACE)
