apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appmesh-gateway
resources:
- namespace.yaml
- deployment.yaml
- rbac.yaml
- service.yaml
configMapGenerator:
  - name: envoy
    files:
      - envoy.yaml
