apiVersion: v1
kind: ServiceAccount
metadata:
  name: appmesh-gateway
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: appmesh-gateway
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["*"]
  - apiGroups:
      - appmesh.k8s.aws
    resources:
      - meshes
      - meshes/status
      - virtualnodes
      - virtualnodes/status
      - virtualservices
      - virtualservices/status
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: appmesh-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appmesh-gateway
subjects:
- kind: ServiceAccount
  name: appmesh-gateway
  namespace: appmesh-gateway
