apiVersion: v1
kind: Service
metadata:
  name: appmesh-gateway
  labels:
    app: appmesh-gateway
  annotations:
    envoy.gateway.kubernetes.io/expose: "false"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: appmesh-gateway
