apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
  annotations:
    envoy.gateway.kubernetes.io/host: "podinfo.local"
    envoy.gateway.kubernetes.io/timeout: "25s"
spec:
  type: ClusterIP
  selector:
    app: podinfo
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
