{{- if .Values.mesh.create }}
apiVersion: appmesh.k8s.aws/v1beta1
kind: Mesh
metadata:
    name: {{ .Values.mesh.name }}
    annotations:
        helm.sh/resource-policy: keep
    labels:
{{ include "appmesh-gateway.labels" . | indent 4 }}
spec:
    serviceDiscoveryType: {{ .Values.mesh.discovery }}
{{- end }}
