apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: kxds
          command:
            - ./kxds
            - kubernetes
            - --port-name=http
            - --namespace=$(POD_NAMESPACE)
