apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: gateway
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gateway
subjects:
- kind: ServiceAccount
  name: gateway

