apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    envoy.gateway.kubernetes.io/expose: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: gateway
