apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway
namePrefix: envoy-
bases:
  - ../base/gateway
resources:
  - namespace.yaml
  - rbac.yaml
patchesStrategicMerge:
  - deployment.yaml

