apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: envoy-gateway
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: envoy-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envoy-gateway
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: envoy-gateway
