apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
generatorOptions:
  disableNameSuffixHash: true
resources:
- deployment.yaml
- rbac.yaml
- service.yaml
configMapGenerator:
  - name: envoy
    files:
      - envoy.yaml
