apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: envoy
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: envoy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: envoy
subjects:
- kind: ServiceAccount
  name: envoy
  namespace: default
