apiVersion: v1
kind: Service
metadata:
  name: tester
  labels:
    app: tester
spec:
  type: ClusterIP
  selector:
    app: tester
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
