name: CI

on: [push, pull_request]

jobs:
  kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate manifests
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            echo "build gateway"
            kustomize build ./kustomize/appmesh-gateway | kubeval --strict --ignore-missing-schemas
            echo "build test"
            kustomize build ./kustomize/test | kubeval --strict --ignore-missing-schemas
  build:
    runs-on: ubuntu-latest
    needs: [kustomize]
    steps:
      - uses: actions/checkout@v1
      - name: Build container
        run: |
          make build-container
