name: PUSH

on: [push]

jobs:
  push-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push container
        run: |
          if [[ "${GITHUB_REF}" == "refs/tags"* ]]; then
            DOCKER_TAG=$(echo ${GITHUB_REF} | rev | cut -d/ -f1 | rev)
            docker build . -t ${{ secrets.DOCKER_USERNAME }}/kxds:${DOCKER_TAG}
            docker push ${{ secrets.DOCKER_USERNAME }}/kxds:${DOCKER_TAG}
          fi
