name: PUSH

on: [push]

jobs:
  push-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Docker Hub
      - uses: azure/container-actions/docker-login@master
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
          - run: |
              DOCKER_TAG="latest"
              if [[ "${GITHUB_REF}" == "refs/tags"* ]]; then
              DOCKER_TAG=$(echo ${GITHUB_REF} | rev | cut -d/ -f1 | rev)
              else
              DOCKER_TAG=$(echo ${GITHUB_REF} | rev | cut -d/ -f1 | rev)-$(echo ${GITHUB_SHA} | head -c7)
              fi
              docker build . -t ${{ secrets.DOCKER_USERNAME }}/kxds:${DOCKER_TAG}
              docker push ${{ secrets.DOCKER_USERNAME }}/kxds:${DOCKER_TAG}
